using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HBD8080A.Core.Services;

internal class InstructionSet8080DAsm {
    internal class Instruction {
        internal byte Opcode;
        internal ushort ImmediateBytes;
        internal string Mnemonic;
    }
    private static readonly Instruction[] instructionSet = new[] {
        new Instruction {Opcode = 0x00, ImmediateBytes = 0, Mnemonic = "NOP"},
        new Instruction {Opcode = 0x01, ImmediateBytes = 2, Mnemonic = "LXI B, "},
        new Instruction {Opcode = 0x11, ImmediateBytes = 2, Mnemonic = "LXI D, "},
        new Instruction {Opcode = 0x21, ImmediateBytes = 2, Mnemonic = "LXI H, "},
        new Instruction {Opcode = 0x31, ImmediateBytes = 2, Mnemonic = "LXI SP, "},
        new Instruction {Opcode = 0x08, ImmediateBytes = 0, Mnemonic = "DB 08H ;(undefined instruction 0x08)"},
        new Instruction {Opcode = 0x10, ImmediateBytes = 0, Mnemonic = "DB 10H ;(undefined instruction 0x10)"},
        new Instruction {Opcode = 0x18, ImmediateBytes = 0, Mnemonic = "DB 18H ;(undefined instruction 0x18)"},
        new Instruction {Opcode = 0x20, ImmediateBytes = 0, Mnemonic = "DB 20H ;(undefined instruction 0x20)"},
        new Instruction {Opcode = 0x28, ImmediateBytes = 0, Mnemonic = "DB 28H ;(undefined instruction 0x28)"},
        new Instruction {Opcode = 0x30, ImmediateBytes = 0, Mnemonic = "DB 30H ;(undefined instruction 0x30)"},
        new Instruction {Opcode = 0x38, ImmediateBytes = 0, Mnemonic = "DB 38H ;(undefined instruction 0x38)"},
        new Instruction {Opcode = 0xCB, ImmediateBytes = 0, Mnemonic = "DB CBH ;(undefined instruction 0xCB)"},
        new Instruction {Opcode = 0xD9, ImmediateBytes = 0, Mnemonic = "DB D9H ;(undefined instruction 0xD9)"},
        new Instruction {Opcode = 0xDD, ImmediateBytes = 0, Mnemonic = "DB DDH ;(undefined instruction 0xDD)"},
        new Instruction {Opcode = 0xED, ImmediateBytes = 0, Mnemonic = "DB EDH ;(undefined instruction 0xED)"},
        new Instruction {Opcode = 0xFD, ImmediateBytes = 0, Mnemonic = "DB FDH ;(undefined instruction 0xFD)"},
        new Instruction {Opcode = 0x02, ImmediateBytes = 0, Mnemonic = "STAX B"},
        new Instruction {Opcode = 0x12, ImmediateBytes = 0, Mnemonic = "STAX D"},
        new Instruction {Opcode = 0x0A, ImmediateBytes = 0, Mnemonic = "LDAX B"},
        new Instruction {Opcode = 0x1A, ImmediateBytes = 0, Mnemonic = "LDAX D"},
        new Instruction {Opcode = 0x03, ImmediateBytes = 0, Mnemonic = "INX B"},
        new Instruction {Opcode = 0x13, ImmediateBytes = 0, Mnemonic = "INX D"},
        new Instruction {Opcode = 0x23, ImmediateBytes = 0, Mnemonic = "INX H"},
        new Instruction {Opcode = 0x33, ImmediateBytes = 0, Mnemonic = "INX SP"},
        new Instruction {Opcode = 0x0B, ImmediateBytes = 0, Mnemonic = "DCX B"},
        new Instruction {Opcode = 0x1B, ImmediateBytes = 0, Mnemonic = "DCX D"},
        new Instruction {Opcode = 0x2B, ImmediateBytes = 0, Mnemonic = "DCX H"},
        new Instruction {Opcode = 0x3B, ImmediateBytes = 0, Mnemonic = "DCX S"},
        new Instruction {Opcode = 0x09, ImmediateBytes = 0, Mnemonic = "DAD B"},
        new Instruction {Opcode = 0x19, ImmediateBytes = 0, Mnemonic = "DAD D"},
        new Instruction {Opcode = 0x29, ImmediateBytes = 0, Mnemonic = "DAD H"},
        new Instruction {Opcode = 0x39, ImmediateBytes = 0, Mnemonic = "DAD S"},
        new Instruction {Opcode = 0x04, ImmediateBytes = 0, Mnemonic = "INR B"},
        new Instruction {Opcode = 0x0C, ImmediateBytes = 0, Mnemonic = "INR C"},
        new Instruction {Opcode = 0x14, ImmediateBytes = 0, Mnemonic = "INR D"},
        new Instruction {Opcode = 0x1C, ImmediateBytes = 0, Mnemonic = "INR E"},
        new Instruction {Opcode = 0x24, ImmediateBytes = 0, Mnemonic = "INR H"},
        new Instruction {Opcode = 0x2C, ImmediateBytes = 0, Mnemonic = "INR L"},
        new Instruction {Opcode = 0x34, ImmediateBytes = 0, Mnemonic = "INR M"},
        new Instruction {Opcode = 0x3C, ImmediateBytes = 0, Mnemonic = "INR A"},
        new Instruction {Opcode = 0x05, ImmediateBytes = 0, Mnemonic = "DCR B"},
        new Instruction {Opcode = 0x0D, ImmediateBytes = 0, Mnemonic = "DCR C"},
        new Instruction {Opcode = 0x15, ImmediateBytes = 0, Mnemonic = "DCR D"},
        new Instruction {Opcode = 0x1D, ImmediateBytes = 0, Mnemonic = "DCR E"},
        new Instruction {Opcode = 0x25, ImmediateBytes = 0, Mnemonic = "DCR H"},
        new Instruction {Opcode = 0x2D, ImmediateBytes = 0, Mnemonic = "DCR L"},
        new Instruction {Opcode = 0x35, ImmediateBytes = 0, Mnemonic = "DCR M"},
        new Instruction {Opcode = 0x3D, ImmediateBytes = 0, Mnemonic = "DCR A"},
        new Instruction {Opcode = 0x06, ImmediateBytes = 1, Mnemonic = "MVI B, "},
        new Instruction {Opcode = 0x0E, ImmediateBytes = 1, Mnemonic = "MVI C, "},
        new Instruction {Opcode = 0x16, ImmediateBytes = 1, Mnemonic = "MVI D, "},
        new Instruction {Opcode = 0x1E, ImmediateBytes = 1, Mnemonic = "MVI E, "},
        new Instruction {Opcode = 0x26, ImmediateBytes = 1, Mnemonic = "MVI H, "},
        new Instruction {Opcode = 0x2E, ImmediateBytes = 1, Mnemonic = "MVI L, "},
        new Instruction {Opcode = 0x36, ImmediateBytes = 1, Mnemonic = "MVI M, "},
        new Instruction {Opcode = 0x3E, ImmediateBytes = 1, Mnemonic = "MVI A, "},
        new Instruction {Opcode = 0x07, ImmediateBytes = 0, Mnemonic = "RLC"},
        new Instruction {Opcode = 0x0F, ImmediateBytes = 0, Mnemonic = "RRC"},
        new Instruction {Opcode = 0x17, ImmediateBytes = 0, Mnemonic = "RAL"},
        new Instruction {Opcode = 0x1F, ImmediateBytes = 0, Mnemonic = "RAR"},
        new Instruction {Opcode = 0x22, ImmediateBytes = 2, Mnemonic = "SHLD"},
        new Instruction {Opcode = 0x2A, ImmediateBytes = 2, Mnemonic = "LHLD"},
        new Instruction {Opcode = 0x27, ImmediateBytes = 0, Mnemonic = "DAA"},
        new Instruction {Opcode = 0x2F, ImmediateBytes = 0, Mnemonic = "CMA"},
        new Instruction {Opcode = 0x32, ImmediateBytes = 2, Mnemonic = "STA"},
        new Instruction {Opcode = 0x3A, ImmediateBytes = 2, Mnemonic = "LDA"},
        new Instruction {Opcode = 0x37, ImmediateBytes = 0, Mnemonic = "STC"},
        new Instruction {Opcode = 0x3F, ImmediateBytes = 0, Mnemonic = "CMC"},
        new Instruction {Opcode = 0x40, ImmediateBytes = 0, Mnemonic = "MOV B, B ;i.e. NOP"},
        new Instruction {Opcode = 0x41, ImmediateBytes = 0, Mnemonic = "MOV B, C"},
        new Instruction {Opcode = 0x42, ImmediateBytes = 0, Mnemonic = "MOV B, D"},
        new Instruction {Opcode = 0x43, ImmediateBytes = 0, Mnemonic = "MOV B, E"},
        new Instruction {Opcode = 0x44, ImmediateBytes = 0, Mnemonic = "MOV B, H"},
        new Instruction {Opcode = 0x45, ImmediateBytes = 0, Mnemonic = "MOV B, L"},
        new Instruction {Opcode = 0x46, ImmediateBytes = 0, Mnemonic = "MOV B, M"},
        new Instruction {Opcode = 0x47, ImmediateBytes = 0, Mnemonic = "MOV B, A"},
        new Instruction {Opcode = 0x48, ImmediateBytes = 0, Mnemonic = "MOV C, B"},
        new Instruction {Opcode = 0x49, ImmediateBytes = 0, Mnemonic = "MOV C, C ;i.e. NOP"},
        new Instruction {Opcode = 0x4A, ImmediateBytes = 0, Mnemonic = "MOV C, D"},
        new Instruction {Opcode = 0x4B, ImmediateBytes = 0, Mnemonic = "MOV C, E"},
        new Instruction {Opcode = 0x4C, ImmediateBytes = 0, Mnemonic = "MOV C, H"},
        new Instruction {Opcode = 0x4D, ImmediateBytes = 0, Mnemonic = "MOV C, L"},
        new Instruction {Opcode = 0x4E, ImmediateBytes = 0, Mnemonic = "MOV C, M"},
        new Instruction {Opcode = 0x4F, ImmediateBytes = 0, Mnemonic = "MOV C, A"},
        new Instruction {Opcode = 0x50, ImmediateBytes = 0, Mnemonic = "MOV D, B"},
        new Instruction {Opcode = 0x51, ImmediateBytes = 0, Mnemonic = "MOV D, C"},
        new Instruction {Opcode = 0x52, ImmediateBytes = 0, Mnemonic = "MOV D, D ;i.e. NOP"},
        new Instruction {Opcode = 0x53, ImmediateBytes = 0, Mnemonic = "MOV D, E"},
        new Instruction {Opcode = 0x54, ImmediateBytes = 0, Mnemonic = "MOV D, H"},
        new Instruction {Opcode = 0x55, ImmediateBytes = 0, Mnemonic = "MOV D, L"},
        new Instruction {Opcode = 0x56, ImmediateBytes = 0, Mnemonic = "MOV D, M"},
        new Instruction {Opcode = 0x57, ImmediateBytes = 0, Mnemonic = "MOV D, A"},
        new Instruction {Opcode = 0x58, ImmediateBytes = 0, Mnemonic = "MOV E, B"},
        new Instruction {Opcode = 0x59, ImmediateBytes = 0, Mnemonic = "MOV E, C"},
        new Instruction {Opcode = 0x5A, ImmediateBytes = 0, Mnemonic = "MOV E, D"},
        new Instruction {Opcode = 0x5B, ImmediateBytes = 0, Mnemonic = "MOV E, E ;i.e. NOP"},
        new Instruction {Opcode = 0x5C, ImmediateBytes = 0, Mnemonic = "MOV E, H"},
        new Instruction {Opcode = 0x5D, ImmediateBytes = 0, Mnemonic = "MOV E, L"},
        new Instruction {Opcode = 0x5E, ImmediateBytes = 0, Mnemonic = "MOV E, M"},
        new Instruction {Opcode = 0x5F, ImmediateBytes = 0, Mnemonic = "MOV E, A"},
        new Instruction {Opcode = 0x60, ImmediateBytes = 0, Mnemonic = "MOV H, B"},
        new Instruction {Opcode = 0x61, ImmediateBytes = 0, Mnemonic = "MOV H, C"},
        new Instruction {Opcode = 0x62, ImmediateBytes = 0, Mnemonic = "MOV H, D"},
        new Instruction {Opcode = 0x63, ImmediateBytes = 0, Mnemonic = "MOV H, E"},
        new Instruction {Opcode = 0x64, ImmediateBytes = 0, Mnemonic = "MOV H, H ;i.e. NOP"},
        new Instruction {Opcode = 0x65, ImmediateBytes = 0, Mnemonic = "MOV H, L"},
        new Instruction {Opcode = 0x66, ImmediateBytes = 0, Mnemonic = "MOV H, M"},
        new Instruction {Opcode = 0x67, ImmediateBytes = 0, Mnemonic = "MOV H, A"},
        new Instruction {Opcode = 0x68, ImmediateBytes = 0, Mnemonic = "MOV L, B"},
        new Instruction {Opcode = 0x69, ImmediateBytes = 0, Mnemonic = "MOV L, C"},
        new Instruction {Opcode = 0x6A, ImmediateBytes = 0, Mnemonic = "MOV L, D"},
        new Instruction {Opcode = 0x6B, ImmediateBytes = 0, Mnemonic = "MOV L, E"},
        new Instruction {Opcode = 0x6C, ImmediateBytes = 0, Mnemonic = "MOV L, H"},
        new Instruction {Opcode = 0x6D, ImmediateBytes = 0, Mnemonic = "MOV L, L ;i.e. NOP"},
        new Instruction {Opcode = 0x6E, ImmediateBytes = 0, Mnemonic = "MOV L, M"},
        new Instruction {Opcode = 0x6F, ImmediateBytes = 0, Mnemonic = "MOV L, A"},
        new Instruction {Opcode = 0x70, ImmediateBytes = 0, Mnemonic = "MOV M, B"},
        new Instruction {Opcode = 0x71, ImmediateBytes = 0, Mnemonic = "MOV M, C"},
        new Instruction {Opcode = 0x72, ImmediateBytes = 0, Mnemonic = "MOV M, D"},
        new Instruction {Opcode = 0x73, ImmediateBytes = 0, Mnemonic = "MOV M, E"},
        new Instruction {Opcode = 0x74, ImmediateBytes = 0, Mnemonic = "MOV M, H"},
        new Instruction {Opcode = 0x75, ImmediateBytes = 0, Mnemonic = "MOV M, L"},
        new Instruction {Opcode = 0x76, ImmediateBytes = 0, Mnemonic = "HLT"},
        new Instruction {Opcode = 0x77, ImmediateBytes = 0, Mnemonic = "MOV M, A"},
        new Instruction {Opcode = 0x78, ImmediateBytes = 0, Mnemonic = "MOV A, B"},
        new Instruction {Opcode = 0x79, ImmediateBytes = 0, Mnemonic = "MOV A, C"},
        new Instruction {Opcode = 0x7A, ImmediateBytes = 0, Mnemonic = "MOV A, D"},
        new Instruction {Opcode = 0x7B, ImmediateBytes = 0, Mnemonic = "MOV A, E"},
        new Instruction {Opcode = 0x7C, ImmediateBytes = 0, Mnemonic = "MOV A, H"},
        new Instruction {Opcode = 0x7D, ImmediateBytes = 0, Mnemonic = "MOV A, L"},
        new Instruction {Opcode = 0x7E, ImmediateBytes = 0, Mnemonic = "MOV A, M"},
        new Instruction {Opcode = 0x7F, ImmediateBytes = 0, Mnemonic = "MOV A, A ;i.e. NOP"},

        new Instruction {Opcode = 0x80, ImmediateBytes = 0, Mnemonic = "ADD"},
        new Instruction {Opcode = 0x88, ImmediateBytes = 0, Mnemonic = "ADC"},
        new Instruction {Opcode = 0x90, ImmediateBytes = 0, Mnemonic = "SUB"},
        new Instruction {Opcode = 0x98, ImmediateBytes = 0, Mnemonic = "SBB"},
        new Instruction {Opcode = 0xA0, ImmediateBytes = 0, Mnemonic = "ANA"},
        new Instruction {Opcode = 0xA8, ImmediateBytes = 0, Mnemonic = "XRA"},
        new Instruction {Opcode = 0xB0, ImmediateBytes = 0, Mnemonic = "ORA"},
        new Instruction {Opcode = 0xB8, ImmediateBytes = 0, Mnemonic = "CMP"},
        new Instruction {Opcode = 0xC0, ImmediateBytes = 0, Mnemonic = "RNZ"},
        new Instruction {Opcode = 0xC1, ImmediateBytes = 0, Mnemonic = "POP"},
        new Instruction {Opcode = 0xC2, ImmediateBytes = 0, Mnemonic = "JNZ"},
        new Instruction {Opcode = 0xC3, ImmediateBytes = 0, Mnemonic = "JMP"},
        new Instruction {Opcode = 0xC4, ImmediateBytes = 0, Mnemonic = "CNZ"},
        new Instruction {Opcode = 0xC5, ImmediateBytes = 0, Mnemonic = "PUSH"},
        new Instruction {Opcode = 0xC6, ImmediateBytes = 0, Mnemonic = "ADI"},
        new Instruction {Opcode = 0xC7, ImmediateBytes = 0, Mnemonic = "RST"},
        new Instruction {Opcode = 0xC8, ImmediateBytes = 0, Mnemonic = "RZ"},
        new Instruction {Opcode = 0xC9, ImmediateBytes = 0, Mnemonic = "RET"},
        new Instruction {Opcode = 0xCA, ImmediateBytes = 0, Mnemonic = "JZ"},  
        new Instruction {Opcode = 0xCC, ImmediateBytes = 0, Mnemonic = "CZ"},
        new Instruction {Opcode = 0xCD, ImmediateBytes = 0, Mnemonic = "CALL"},
        new Instruction {Opcode = 0xCE, ImmediateBytes = 0, Mnemonic = "ACI"},
        new Instruction {Opcode = 0xD0, ImmediateBytes = 0, Mnemonic = "RNC"},
        new Instruction {Opcode = 0xD2, ImmediateBytes = 0, Mnemonic = "JNC"},
        new Instruction {Opcode = 0xD3, ImmediateBytes = 0, Mnemonic = "OUT"},
        new Instruction {Opcode = 0xD4, ImmediateBytes = 0, Mnemonic = "CNC"},
        new Instruction {Opcode = 0xD6, ImmediateBytes = 0, Mnemonic = "SUI"},
        new Instruction {Opcode = 0xD8, ImmediateBytes = 0, Mnemonic = "RC"},
        new Instruction {Opcode = 0xDA, ImmediateBytes = 0, Mnemonic = "JC"},
        new Instruction {Opcode = 0xDB, ImmediateBytes = 0, Mnemonic = "IN"},
        new Instruction {Opcode = 0xDC, ImmediateBytes = 0, Mnemonic = "CC"},
        new Instruction {Opcode = 0xDE, ImmediateBytes = 0, Mnemonic = "SBI"},
        new Instruction {Opcode = 0xE0, ImmediateBytes = 0, Mnemonic = "RPO"},
        new Instruction {Opcode = 0xE2, ImmediateBytes = 0, Mnemonic = "JPO"},
        new Instruction {Opcode = 0xE3, ImmediateBytes = 0, Mnemonic = "XTHL"},
        new Instruction {Opcode = 0xE4, ImmediateBytes = 0, Mnemonic = "CPO"},
        new Instruction {Opcode = 0xE6, ImmediateBytes = 0, Mnemonic = "ANI"},
        new Instruction {Opcode = 0xE8, ImmediateBytes = 0, Mnemonic = "RPE"},
        new Instruction {Opcode = 0xE9, ImmediateBytes = 0, Mnemonic = "PCHL"},
        new Instruction {Opcode = 0xEA, ImmediateBytes = 0, Mnemonic = "JPE"},
        new Instruction {Opcode = 0xEB, ImmediateBytes = 0, Mnemonic = "XCHG"},
        new Instruction {Opcode = 0xEC, ImmediateBytes = 0, Mnemonic = "CPE"},
        new Instruction {Opcode = 0xEE, ImmediateBytes = 0, Mnemonic = "XRI"},
        new Instruction {Opcode = 0xF0, ImmediateBytes = 0, Mnemonic = "RPO"},
        new Instruction {Opcode = 0xF2, ImmediateBytes = 0, Mnemonic = "JPO"},
        new Instruction {Opcode = 0xF3, ImmediateBytes = 0, Mnemonic = "DI"},
        new Instruction {Opcode = 0xF4, ImmediateBytes = 0, Mnemonic = "CP"},
        new Instruction {Opcode = 0xF6, ImmediateBytes = 0, Mnemonic = "ORI"},
        new Instruction {Opcode = 0xF8, ImmediateBytes = 0, Mnemonic = "RM"},
        new Instruction {Opcode = 0xF9, ImmediateBytes = 0, Mnemonic = "SPHL"},
        new Instruction {Opcode = 0xFA, ImmediateBytes = 0, Mnemonic = "JM"},
        new Instruction {Opcode = 0xFB, ImmediateBytes = 0, Mnemonic = "EI"},
        new Instruction {Opcode = 0xFC, ImmediateBytes = 0, Mnemonic = "CM"},
        new Instruction {Opcode = 0xFE, ImmediateBytes = 0, Mnemonic = "CPI"}
    };

}
